Fixed erroneous username selection
Fixed erroneous username selection when username contained a number

diff --git a/no-readme b/no-readme
--- a/no-readme
+++ b/no-readme
@@ -1,11 +1,11 @@
 #!/bin/bash
 # ----------------------------------------------------------------------------------------------------
 # no-readme | simple script to null/enable readme.* and license.* files on a cPanel server
-# no-readme Version: 1.1
-# Github: https://github.com/InterGenStudios/no-readme
+# no-readme Version: 3.0
+# GitLab: https://git.intergen.us/intergen/No-ReadMe
 # ---------------------------------------------------
-# InterGenStudios: 10-17-15
-# Copyright (c) 2015: Christopher 'InterGen' Cork - InterGenStudios
+# InterGenStudios: 01-23-2019
+# Copyright (c) 2019: Christopher 'InterGen' Cork - InterGenStudios
 # URL: https://intergenstudios.com
 # --------------------------------
 # License: GPL-2.0+
@@ -24,33 +24,17 @@
 ##---------------------------------------##
 ###########################################
 
-# Simple regex for number checking
 RE='^[0-9]+$'
-
-# Output red text
 RED="\e[1m\e[31m"
-
-# Output Green text
 GREEN="\e[1m\e[32m"
-
-# Output Yellow text
 YELLOW="\e[1m\e[33m"
-
-# Output Blue text
 BLUE="\e[1m\e[34m"
-
-# Output Bold White text
 WHITE="\e[1m\e[37m"
-
-# Remove any previously set text colors
 NOCOLOR="\e[0m"
 
-# no-readme version number
-vers=1.1
+vers=2.0
 
-# Load's userlist variable
 USERLIST="$(grep \: /etc/trueuserdomains | grep -v nobody | awk '{print $2}' | uniq)"
-export USERLIST
 
 #########################################
 ##-------------------------------------##
@@ -68,21 +52,18 @@ export USERLIST
 # BEGIN - DISPLAY LAYOUT FUNCTIONS #
 #----------------------------------#
 
-# A simple divider
 SEPARATOR () {
-    echo -e "\n\n${BLUE}------------------------------------------------------------------------------${NOCOLOR}\n\n"
+  echo -e "\n\n${BLUE}------------------------------------------------------------------------------${NOCOLOR}\n\n"
 }
 
-# A simple divider
 SPACER () {
-    echo -e "\n${BLUE}----------------------------------\n${NOCOLOR}"
+  echo -e "\n${BLUE}----------------------------------\n${NOCOLOR}"
 }
 
-# Creates uniform look during script execution when called after any clear command
 HEADER () {
-    echo -e "\n\n${BLUE}_________________________________________________________________________________________${NOCOLOR}\n"
-    echo -e "${WHITE}    No-ReadMe v${GREEN}${vers}${NOCOLOR}"
-    echo -e "${BLUE}_________________________________________________________________________________________${NOCOLOR}\n\n"
+  echo -e "\n\n${BLUE}_________________________________________________________________________________________${NOCOLOR}\n"
+  echo -e "${WHITE}    No-ReadMe v${GREEN}${vers}${NOCOLOR}"
+  echo -e "${BLUE}_________________________________________________________________________________________${NOCOLOR}\n\n"
 }
 
 #--------------------------------#
@@ -90,215 +71,178 @@ HEADER () {
 #--------------------------------#
 
 CHECK_FOR_ROOT () {
-    if [ "$(id -u)" != "0" ]; then
-
+  if [ "$(id -u)" != "0" ]; then
     echo -e "\n\n    ${RED}${BLINK}--------${NOCOLOR}"
-    echo -e "    ${RED}${BLINK}WARNING!${NOCOLOR}"
-    echo -e "    ${RED}${BLINK}--------${NOCOLOR}\n\n"
-    echo -e "    ${WHITE}no-readme must be run as ${RED}${UNDERLINE_TEXT}root${NOCOLOR}\n\n"
+    echo -e "    ${RED}WARNING!${NOCOLOR}"
+    echo -e "    ${RED}--------${NOCOLOR}\n\n"
+    echo -e "    ${WHITE}No-ReadMe must be run as ${RED}root${NOCOLOR}\n\n"
     echo -e "    (Exiting now...)\n\n"
     exit 1
-
-    fi
+  fi
 }
 
 BLOCK_SINGLE_USER () {
-    clear
-    HEADER
-    find /home/"$user" -type f -iname "readme.*" -o -iname "license.*" >> filelist
-    if [ "$(wc -l < filelist)" == "0" ]; then
-
-        echo -e "\n\n  No ${WHITE}README.*${NOCOLOR} or ${WHITE}LICENSE.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR}\n\n  ${GREEN}Run complete${NOCOLOR}\n\n"
-
-    else
-
-        echo -e "\n\n  Checking files for user ${YELLOW}${user}${NOCOLOR}...\n\n"
-        grep -v '^ *#' < filelist | while IFS= read -r file; do
-
-            chown root:root "$file" && chmod 000 "$file"
-
-        done
-        echo -e "  All ${WHITE}README.*${NOCOLOR} and ${WHITE}LICENSE.*${NOCOLOR} files have been blocked for user ${YELLOW}${user}${NOCOLOR}\n\n  ${GREEN}Run complete${NOCOLOR}\n\n"
-        rm filelist
-
-    fi
+  clear
+  HEADER
+  echo -e "\n  Checking files for user ${YELLOW}${user}${NOCOLOR}...\n"
+  if [[ $(find /home/"$user" -type f -iname "readme.*" | wc -l) > 0 ]]; then
+    find /home/"$user" -type f -iname "readme.*" \( -exec chmod 000 {} \; -o -exec true \; \) -exec chown root:root {} \;
+    echo -e "\n  All ${WHITE}README.*${NOCOLOR} files have been blocked for user ${YELLOW}${user}${NOCOLOR}"
+  else
+    echo -e "\n  No ${WHITE}README.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR}, skipping..."
+  fi
+  if [[ $(find /home/"$user" -type f -iname "license.*" | wc -l) > 0 ]]; then
+    find /home/"$user" -type f -iname "license.*" \( -exec chmod 000 {} \; -o -exec true \; \) -exec chown root:root {} \;
+    echo -e "\n  All ${WHITE}LICENSE.*${NOCOLOR} files have been blocked for user ${YELLOW}${user}${NOCOLOR}"
+  else
+    echo -e "\n  No ${WHITE}LICENSE.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR}, skipping..."
+  fi
+  echo -e "\n\n  ${GREEN}Run complete${NOCOLOR}\n\n"
 }
 
 BLOCK_ALL_USERS () {
-    clear
-    HEADER
-    for user in ${USERLIST[@]}; do
-
-        find /home/"$user" -type f -iname "readme.*" -o -iname "license.*" >> "$user"_filelist
-        if [ "$(wc -l < ${user}_filelist)" == "0" ]; then
-
-            echo -e "\n  No ${WHITE}README.*${NOCOLOR} or ${WHITE}LICENSE.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR} - ${WHITE}skipping...${NOCOLOR}\n"
-            SPACER
-
-        else
-
-            echo -e "\n  Checking files for user ${YELLOW}${user}${NOCOLOR}...\n"
-            grep -v '^ *#' < "$user"_filelist | while IFS= read -r file; do
-
-                chown root:root "$file" && chmod 000 "$file"
-
-            done
-            echo -e "  All ${WHITE}README.*${NOCOLOR} and ${WHITE}LICENSE.*${NOCOLOR} files have been blocked for user ${YELLOW}${user}${NOCOLOR}\n"
-            rm "$user"_filelist
-            SPACER
-
-        fi
-
-    done
-    echo -e "\n\n  All ${WHITE}README.*${NOCOLOR} and ${WHITE}LICENSE.*${NOCOLOR} files have been blocked\n\n  ${GREEN}Run complete${NOCOLOR}\n\n"
+  clear
+  HEADER
+  for user in ${USERLIST[@]}; do
+    echo -e "\n  Checking files for user ${YELLOW}${user}${NOCOLOR}...\n"
+    if [[ $(find /home/"$user" -type f -iname "readme.*" | wc -l) > 0 ]]; then
+      find /home/"$user" -type f -iname "readme.*" \( -exec chmod 000 {} \; -o -exec true \; \) -exec chown root:root {} \;
+      echo -e "\n  All ${WHITE}README.*${NOCOLOR} files have been blocked for user ${YELLOW}${user}${NOCOLOR}"
+    else
+      echo -e "\n  No ${WHITE}README.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR}, skipping..."
+    fi
+    if [[ $(find /home/"$user" -type f -iname "license.*" | wc -l) > 0 ]]; then
+      find /home/"$user" -type f -iname "license.*" \( -exec chmod 000 {} \; -o -exec true \; \) -exec chown root:root {} \;
+      echo -e "\n  All ${WHITE}LICENSE.*${NOCOLOR} files have been blocked for user ${YELLOW}${user}${NOCOLOR}"
+    else
+      echo -e "\n  No ${WHITE}LICENSE.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR}, skipping..."
+    fi
+    SPACER
+  done
+  echo -e "\n\n  All ${WHITE}README.*${NOCOLOR} and ${WHITE}LICENSE.*${NOCOLOR} files have been blocked\n\n  ${GREEN}Run complete${NOCOLOR}\n\n"
 }
 
 UNBLOCK_SINGLE_USER () {
-    clear
-    HEADER
-    find /home/"$user" -type f -iname "readme.*" -o -iname "license.*" >> filelist
-    if [ "$(wc -l < filelist)" == "0" ]; then
-
-        echo -e "\n\n  No ${WHITE}README.*${NOCOLOR} or ${WHITE}LICENSE.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR}\n\n  ${GREEN}Run complete${NOCOLOR}\n\n"
-
-    else
-
-        echo -e "\n\n  Checking files for user ${YELLOW}${user}${NOCOLOR}...\n\n"
-        grep -v '^ *#' < filelist | while IFS= read -r file; do
-
-            chown "$user":"$user" "$file" && chmod 644 "$file"
-
-        done
-        echo -e "  All ${WHITE}README.*${NOCOLOR} and ${WHITE}LICENSE.*${NOCOLOR} files have been unblocked for user ${YELLOW}${user}${NOCOLOR}\n\n  ${GREEN}Run complete${NOCOLOR}\n\n"
-        rm filelist
-
-    fi
+  clear
+  HEADER
+  echo -e "\n  Checking files for user ${YELLOW}${user}${NOCOLOR}...\n"
+  if [[ $(find /home/"$user" -type f -iname "readme.*" | wc -l) > 0 ]]; then
+    find /home/"$user" -type f -iname "readme.*" \( -exec chmod 644 {} \; -o -exec true \; \) -exec chown "$user":"$user" {} \;
+    echo -e "\n  All ${WHITE}README.*${NOCOLOR} files have been unblocked for user ${YELLOW}${user}${NOCOLOR}"
+  else
+    echo -e "\n  No ${WHITE}README.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR}, skipping..."
+  fi
+  if [[ $(find /home/"$user" -type f -iname "license.*" | wc -l) > 0 ]]; then
+    find /home/"$user" -type f -iname "license.*" \( -exec chmod 644 {} \; -o -exec true \; \) -exec chown "$user":"$user" {} \;
+    echo -e "\n  All ${WHITE}LICENSE.*${NOCOLOR} files have been unblocked for user ${YELLOW}${user}${NOCOLOR}"
+  else
+    echo -e "\n  No ${WHITE}LICENSE.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR}, skipping..."
+  fi
+  echo -e "\n\n  ${GREEN}Run complete${NOCOLOR}\n\n"
 }
 
 UNBLOCK_ALL_USERS () {
-    clear
-    HEADER
-    for user in ${USERLIST[@]}; do
-
-        find /home/"$user" -type f -iname "readme.*" -o -iname "license.*" >> "$user"_filelist
-        if [ "$(wc -l < ${user}_filelist)" == "0" ]; then
-
-            echo -e "\n  No ${WHITE}README.*${NOCOLOR} or ${WHITE}LICENSE.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR} - ${WHITE}skipping...${NOCOLOR}\n"
-            SPACER
-
-        else
-
-            echo -e "\n  Checking files for user ${YELLOW}${user}${NOCOLOR}...\n"
-            grep -v '^ *#' < "$user"_filelist | while IFS= read -r file; do
-
-                chown "$user":"$user" "$file" && chmod 644 "$file"
-
-            done
-            echo -e "  All ${WHITE}README.*${NOCOLOR} and ${WHITE}LICENSE.*${NOCOLOR} files have been unblocked for user ${YELLOW}${user}${NOCOLOR}\n"
-            rm "$user"_filelist
-            SPACER
-
-        fi
-
-    done
-    echo -e "\n\n  All ${WHITE}README.*${NOCOLOR} and ${WHITE}LICENSE.*${NOCOLOR} files have been unblocked\n\n  ${GREEN}Run complete${NOCOLOR}\n\n"
+  clear
+  HEADER
+  for user in ${USERLIST[@]}; do
+    echo -e "\n  Checking files for user ${YELLOW}${user}${NOCOLOR}...\n"
+    if [[ $(find /home/"$user" -type f -iname "readme.*" | wc -l) > 0 ]]; then
+      find /home/"$user" -type f -iname "readme.*" \( -exec chmod 644 {} \; -o -exec true \; \) -exec chown "$user":"$user" {} \;
+      echo -e "\n  All ${WHITE}README.*${NOCOLOR} files have been unblocked for user ${YELLOW}${user}${NOCOLOR}"
+    else
+      echo -e "\n  No ${WHITE}README.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR}, skipping..."
+    fi
+    if [[ $(find /home/"$user" -type f -iname "license.*" | wc -l) > 0 ]]; then
+      find /home/"$user" -type f -iname "license.*" \( -exec chmod 644 {} \; -o -exec true \; \) -exec chown "$user":"$user" {} \;
+      echo -e "\n  All ${WHITE}LICENSE.*${NOCOLOR} files have been unblocked for user ${YELLOW}${user}${NOCOLOR}"
+    else
+      echo -e "\n  No ${WHITE}LICENSE.*${NOCOLOR} files found for user ${YELLOW}${user}${NOCOLOR}, skipping..."
+    fi
+    SPACER
+  done
+  echo -e "\n\n  All ${WHITE}README.*${NOCOLOR} and ${WHITE}LICENSE.*${NOCOLOR} files have been unblocked\n\n  ${GREEN}Run complete${NOCOLOR}\n\n"
 }
 
 ROUTE () {
-    clear
-    HEADER
-    echo -e "\n\n  ${WHITE}What would you like to modify?${NOCOLOR}\n\n"
-    echo -e "  ${WHITE}1)${NOCOLOR} The Entire Server\n"
-    echo -e "  ${WHITE}2)${NOCOLOR} A Single User\n\n"
-    echo -en "  ${WHITE}[${NOCOLOR} Enter Selection ${WHITE}]:${NOCOLOR} "
-    read -r SelectionA
-
-    case "$SelectionA" in
-
-        1) clear
-           HEADER
-           echo -e "\n\n  ${WHITE}Choose an operation:${NOCOLOR}\n\n"
-           echo -e "  ${WHITE}1)${NOCOLOR} Blocking\n"
-           echo -e "  ${WHITE}2)${NOCOLOR} Unblocking\n\n"
-           echo -en "  ${WHITE}[${NOCOLOR} Enter Selection ${WHITE}]:${NOCOLOR} "
-           read -r SelectionB
-
-           case "$SelectionB" in
-
-               1) BLOCK_ALL_USERS
+  clear
+  HEADER
+  echo -e "\n\n  ${WHITE}What would you like to modify?${NOCOLOR}\n\n"
+  echo -e "  ${WHITE}1)${NOCOLOR} The Entire Server\n"
+  echo -e "  ${WHITE}2)${NOCOLOR} A Single User\n\n"
+  echo -en "  ${WHITE}[${NOCOLOR} Enter Selection ${WHITE}]:${NOCOLOR} "
+  read -r SelectionA
+  case "$SelectionA" in
+    1)  clear
+        HEADER
+        echo -e "\n\n  ${WHITE}Choose an operation:${NOCOLOR}\n\n"
+        echo -e "  ${WHITE}1)${NOCOLOR} Blocking\n"
+        echo -e "  ${WHITE}2)${NOCOLOR} Unblocking\n\n"
+        echo -en "  ${WHITE}[${NOCOLOR} Enter Selection ${WHITE}]:${NOCOLOR} "
+        read -r SelectionB
+        case "$SelectionB" in
+          1)  BLOCK_ALL_USERS
+              ;;
+          2) UNBLOCK_ALL_USERS
+              ;;
+        esac
+        ;;
+    2)  clear
+        HEADER
+        echo -e "\n\n  ${WHITE}Which user would you like to modify?${NOCOLOR}\n\n"
+        readarray newlist < userlist
+        SEPARATOR
+        for ((i = 0; i < ${#newlist[@]}; ++i)); do
+            position=$(( $i + 1 ))
+            echo "$position   ${newlist[$i]}"
+        done
+        SEPARATOR
+        echo -en "\n  Select Domain [${WHITE}q for quit${NOCOLOR}]: "
+        read -r userchoice
+        selector=$(( $userchoice - 1 ))
+        user="$(echo ${newlist[$selector]} | tr -d '\n')"
+        if [ "$userchoice" = "Q" ] || [ "$userchoice" = "q" ]; then
+          echo -e "\n  ${YELLOW}Quiting...${NOCOLOR}\n\n"
+          sleep 1
+          exit 1
+        else
+          if ! [[ $userchoice =~ $RE ]]; then
+            echo -e "\n  ${RED}Invalid selection\n  Restarting...${NOCOLOR}\n\n"
+            sleep 2
+            ROUTE
+          else
+            clear
+            HEADER
+            echo -e "\n\n  ${WHITE}Choose an operation to perform on ${NOCOLOR}/home/${YELLOW}${user}${NOCOLOR}:\n\n"
+            echo -e "  ${WHITE}1)${NOCOLOR} Block\n"
+            echo -e "  ${WHITE}2)${NOCOLOR} Unblock\n\n"
+            echo -en "  ${WHITE}[${NOCOLOR} Enter Selection ${WHITE}]:${NOCOLOR} "
+            read -r SelectionC
+            case "$SelectionC" in
+              1)  BLOCK_SINGLE_USER
                   ;;
-               2) UNBLOCK_ALL_USERS
+              2)  UNBLOCK_SINGLE_USER
                   ;;
-
-           esac
-           ;;
-        2) clear
-           HEADER
-           echo -e "\n\n  ${WHITE}Which user would you like to modify?${NOCOLOR}\n\n"
-           sed = userlist | sed 'N;s/\n/\t/' > userchoices
-           SEPARATOR
-           cat userchoices
-           SEPARATOR
-           echo -en "\n  Select Domain [${WHITE}q for quit${NOCOLOR}]: "
-           read -r userchoice
-           user="$(grep -m 1 "${userchoice}" userchoices | awk '{print $2}')"
-
-           if [ "$userchoice" = "Q" ] || [ "$userchoice" = "q" ]; then
-
-               echo -e "\n  ${YELLOW}Quiting...${NOCOLOR}\n\n"
-               sleep 1
-               exit 1
-
-           else
-
-               if ! [[ $userchoice =~ $RE ]]; then
-
-                   echo -e "\n  ${RED}Invalid selection\n  Restarting...${NOCOLOR}\n\n"
-                   sleep 2
-                   ROUTE
-
-               else
-
-                   clear
-                   HEADER
-                   echo -e "\n\n  ${WHITE}Choose an operation to perform on ${NOCOLOR}/home/${YELLOW}${user}${NOCOLOR}:\n\n"
-                   echo -e "  ${WHITE}1)${NOCOLOR} Block\n"
-                   echo -e "  ${WHITE}2)${NOCOLOR} Unblock\n\n"
-                   echo -en "  ${WHITE}[${NOCOLOR} Enter Selection ${WHITE}]:${NOCOLOR} "
-                   read -r SelectionC
-
-                   case "$SelectionC" in
-
-                       1) BLOCK_SINGLE_USER
-                          ;;
-                       2) UNBLOCK_SINGLE_USER
-                          ;;
-
-                   esac
-
-               fi
-
-           rm userchoices
-           fi
-           ;;
-
-    esac
+            esac
+          fi
+        fi
+      ;;
+  esac
 }
 
 HELPTEXT () {
-    clear
-    HEADER
-    echo -e "\n  ${WHITE}No-ReadMe ${GREEN}HELP${NOCOLOR}:"
-    echo -e "  ${GREEN}---------------${NOCOLOR}\n"
-    echo -e "  Nulls/resets permissions on all ${WHITE}readme.${GREEN}* ${NOCOLOR}and ${WHITE}license.${GREEN}* ${NOCOLOR}files\n"
-    echo -e "  ${GREEN}---------------${NOCOLOR}\n"
-    echo -e "  ${WHITE}USAGE: ${NOCOLOR}no-readme ${WHITE}[${NOCOLOR}options${WHITE}]${NOCOLOR}\n"
-    echo -e "  ${WHITE}Options:${NOCOLOR}\n"
-    echo -e "  ${GREEN}-b${NOCOLOR}: Block all ${WHITE}readme.${GREEN}* ${NOCOLOR}and ${WHITE}license.${GREEN}*${NOCOLOR} user files on server ${WHITE}(${YELLOW}NO TERMINAL OUTPUT${WHITE})${NOCOLOR}"
-    echo -e "  ${GREEN}-u${NOCOLOR}: Restore all ${WHITE}readme.${GREEN}* ${NOCOLOR}and ${WHITE}license.${GREEN}*${NOCOLOR} user files on server ${WHITE}(${YELLOW}NO TERMINAL OUTPUT${WHITE})${NOCOLOR}"
-    echo -e "  ${GREEN}-h${NOCOLOR}: Display this helptext and exit"
-    echo -e "  ${GREEN}-m${NOCOLOR}: Menu driven operation\n\n"
-    exit 0
+  clear
+  HEADER
+  echo -e "\n  ${WHITE}No-ReadMe ${GREEN}HELP${NOCOLOR}:"
+  echo -e "  ${GREEN}---------------${NOCOLOR}\n"
+  echo -e "  Nulls/resets permissions on all ${WHITE}readme.${GREEN}* ${NOCOLOR}and ${WHITE}license.${GREEN}* ${NOCOLOR}files\n"
+  echo -e "  ${GREEN}---------------${NOCOLOR}\n"
+  echo -e "  ${WHITE}USAGE: ${NOCOLOR}no-readme ${WHITE}[${NOCOLOR}options${WHITE}]${NOCOLOR}\n"
+  echo -e "  ${WHITE}Options:${NOCOLOR}\n"
+  echo -e "  ${GREEN}-b${NOCOLOR}: Block all ${WHITE}readme.${GREEN}* ${NOCOLOR}and ${WHITE}license.${GREEN}*${NOCOLOR} user files on server ${WHITE}(${YELLOW}NO TERMINAL OUTPUT${WHITE})${NOCOLOR}"
+  echo -e "  ${GREEN}-u${NOCOLOR}: Restore all ${WHITE}readme.${GREEN}* ${NOCOLOR}and ${WHITE}license.${GREEN}*${NOCOLOR} user files on server ${WHITE}(${YELLOW}NO TERMINAL OUTPUT${WHITE})${NOCOLOR}"
+  echo -e "  ${GREEN}-h${NOCOLOR}: Display this helptext and exit"
+  echo -e "  ${GREEN}-m${NOCOLOR}: Menu driven operation\n\n"
+  exit 0
 }
 
 ############################
@@ -313,21 +257,29 @@ HELPTEXT () {
 ##---------------------##
 #########################
 
-# Create userlist file for use in subshells
 CHECK_FOR_ROOT
+
 grep \: /etc/trueuserdomains | grep -v nobody | awk '{print $2}' | uniq > userlist
-# Cli usage options
+
 case $1 in
-    -b) BLOCK_ALL_USERS > /dev/null 2>&1
-        ;;
-    -u) UNBLOCK_ALL_USERS > /dev/null 2>&1
-        ;;
-    -m) ROUTE
-        ;;
-     *) HELPTEXT
-        ;;
+  -b) BLOCK_ALL_USERS > /dev/null 2>&1
+      ;;
+  -u) UNBLOCK_ALL_USERS > /dev/null 2>&1
+      ;;
+  -h) HELPTEXT
+      ;;
+  --h) HELPTEXT
+      ;;
+  -help) HELPTEXT
+      ;;
+  --help) HELPTEXT
+      ;;
+  -m) ROUTE
+      ;;
+  *) HELPTEXT
+      ;;
 esac
-# cleanup
+
 rm userlist
 
 #######################
